jobs:
- job: LINUX_GCC
  displayName: 'Linux (amd64; Trusty; GCC)'
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
    - task: docker@0
      displayName: Build
      inputs:
      action: 'Run an image'
      imageName: darktable/darktable
      volumes: |
       $(Build.SourcesDirectory):/src
       $(Build.BinariesDirectory):/build
      envVars:
        CC=gcc
      workDir: '/build'
      detached: false
  - job: WINDOWS
    timeoutInMinutes: 60
    pool:
      vmImage: vs2017-win2016
    strategy:
      matrix:
        x86_64:
          MSYSTEM: MINGW64
          MSYS2_ARCH: x86_64
    steps:
      - checkout: self
        clean: true
        submodules: true
        displayName: Checkout darktable sources
      - script: |
          choco install msys2 --params="/InstallDir:%CD:~0,2%\msys64 /NoUpdate /NoPath"
        displayName: Install MSYS2
      - script: |
          set PATH=%CD:~0,2%\msys64\usr\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem
          %CD:~0,2%\msys64\usr\bin\pacman --noconfirm -Syyuu
          %CD:~0,2%\msys64\usr\bin\pacman --noconfirm -Syuu
        displayName: Update MSYS2
      - script: |
          set PATH=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem
          %CD:~0,2%\msys64\usr\bin\bash -lc ".ci/ci-script-windows2.sh"
        displayName: Install Depdendencies
        env:
          MSYS2_ARCH: $(MSYS2_ARCH)
          MSYSTEM: $(MSYSTEM)
          CHERE_INVOKING: yes
      - script: |
          set PATH=%CD:~0,2%\msys64\mingw64\bin;%CD:~0,2%\msys64\usr\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem
          %CD:~0,2%\msys64\usr\bin\bash -lc ".ci/ci-script-build.sh"
        displayName: Build darktable        
        env:
          MSYS2_ARCH: $(MSYS2_ARCH)
          MSYSTEM: $(MSYSTEM)
          CHERE_INVOKING: yes
