jobs:
  - job: LINUX_GCC
    displayName: 'LINUX (amd64; Trusty; GCC)'
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
      - checkout: self
        clean: true
        submodules: true
        displayName: Checkout darktable sources    
      - bash: docker pull darktable/darktable
        displayName: Pull Docker image for build
        failOnStderr: false
      - task: docker@1
        displayName: Compile in Linux container
        inputs:
          command: run
          imageName: darktable/darktable
          volumes: |
            $(Build.SourcesDirectory):/build/darktable
            $(Build.BinariesDirectory):/build/darktable-build
          containerCommand: /build/darktable/.ci/ci-script.sh
          workingDirectory: '/build/darktable-build'
          runInBackground: false
          arguments:
            --tmpfs=/build/darktable-install
          envVars: |
            CC=gcc-8 
            CXX=g++-8
            CFLAGS=-pipe
            CXXFLAGS=-pipe
            TARGET=build
            INSTALL_PREFIX=/build/darktable-build
            SRC_DIR=/build/darktable
            BUILD_DIR=/build/darktable-build
  - job: MACOS_GCC
    displayName: 'MacOS (macOS X Mojave 10.14; GCC)'
    pool:
      vmImage: 'macOS-10.14'
    steps:
      - checkout: self
        clean: true
        submodules: true
        displayName: Checkout darktable sources
      - bash: brew update && brew tap Homebrew/bundle && cd .ci && brew bundle --verbose
        displayName: Update Brew and install dependencies
        failOnStderr: false
      - bash: . mkdir "$BUILD_DIR"
        workingDirectory: "$SRC_DIR"
      - bash: . "$SRC_DIR/.ci/ci-script-build.sh"
        displayName: Build darktable       
        workingDirectory: "$BUILD_DIR"
        env:
          CC=gcc-7
          CXX=g++-7
          CFLAGS=-pipe
          CXXFLAGS=-pipe
          TARGET=build
          INSTALL_PREFIX=/build/darktable-build
          SRC_DIR=/build/darktable
          BUILD_DIR=/build/darktable-build       
  - job: WINDOWS
    displayName: 'WINDOWS (x86_64; GCC)'
    timeoutInMinutes: 60
    pool:
      vmImage: vs2017-win2016
    strategy:
      matrix:
        x86_64:
          MSYSTEM: MINGW64
          MSYS2_ARCH: x86_64
    steps:
      - checkout: self
        clean: true
        submodules: true
        displayName: Checkout darktable sources
      - script: |
          choco install msys2 --params="/InstallDir:%CD:~0,2%\msys64 /NoUpdate /NoPath"
        displayName: Install MSYS2
      - script: |
          set PATH=%CD:~0,2%\msys64\usr\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem
          %CD:~0,2%\msys64\usr\bin\pacman --noconfirm -Syyuu
          %CD:~0,2%\msys64\usr\bin\pacman --noconfirm -Syuu
        displayName: Update MSYS2
      - script: |
          set PATH=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem
          %CD:~0,2%\msys64\usr\bin\bash -lc ".ci/ci-script-windows2.sh"
        displayName: Install Depdendencies
        env:
          MSYS2_ARCH: $(MSYS2_ARCH)
          MSYSTEM: $(MSYSTEM)
          CHERE_INVOKING: yes
      - script: |
          set PATH=%CD:~0,2%\msys64\mingw64\bin;%CD:~0,2%\msys64\usr\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem
          %CD:~0,2%\msys64\usr\bin\bash -lc ".ci/ci-script-build.sh"
        displayName: Build darktable        
        env:
          MSYS2_ARCH: $(MSYS2_ARCH)
          MSYSTEM: $(MSYSTEM)
          CHERE_INVOKING: yes
